Locales['da'] = {
    -- Logs
    ['logs:admin::create:title'] = 'Oprettet Ny Bande',
    ['logs:admin::create'] = '%s har oprettet en ny bande\nNavn: %s\nLabel: %s\nPenge: %s\nMax Members: %s\nMax Pushers: %s',
    ['logs:admin::edit:title'] = 'Ændret På Bande',
    ['logs:admin::edit'] = '%s har lavet ændringer på bande %s\nPenge: %s\nMax Members: %s\nMax Pushers: %s',
    ['logs:admin::delete:title'] = 'Slettet Bande',
    ['logs:admin::delete'] = '%s slettede banden %s (%s)',
    ['logs:admin::setboss:title'] = 'Satte Bande Boss',
    ['logs:admin::setboss'] = '%s gjorde %s til boss af banden %s',
    ['logs:money::insert:title'] = 'Tilføjede Penge Til Bande Kasse',
    ['logs:money::insert'] = '%s tilføjede %s DKK til %s bande kasse',
    ['logs:money::take:title'] = 'Fjernede Penge Fra Bande Kasse',
    ['logs:money::take'] = '%s fjernede %s DKK fra %s bande kasse',
    ['logs:gang::addmember:title'] = 'Tilføjede Medlem Til Banden',
    ['logs:gang::addmember'] = '%s tilføjede %s til banden %s som %s',
    ['logs:gang::removemember:title'] = 'Fjernede Medlem Fra Banden',
    ['logs:gang::removemember'] = '%s fjernede %s fra banden %s',
    ['logs:shop::buyitem:title'] = 'Købte I Bande Shoppen',
    ['logs:shop::buyitem'] = '%s købte %sx %s\nBande: %s',

    -- Admin
    ['admin:createGang:menu:title'] = 'Opret Bande',
    ['admin:createGang:menu::name'] = 'Navn: %s',
    ['admin:createGang:menu::label'] = 'Label: %s',
    ['admin:createGang:menu::money'] = 'Bandekasse: %s',
    ['admin:createGang:menu::maxMembers'] = 'Bande Medlemmer: %s',
    ['admin:createGang:menu::maxPushers'] = 'Pushere: %s',
    ['admin:createGang:menu::locations'] = 'Lokationer',
    ['admin:createGang:menu::create'] = 'Opret Bande',
    ['admin:createGang:menu:setLabel'] = 'Bande Label',
    ['admin:createGang:gangCreated'] = 'Du oprettede banden %s',
    ['admin:setGangBoss'] = 'Du satte %s (%s) til at være boss af banden %s',
    ['admin:setGangBoss:command::help'] = 'Sæt spiller til at være boss af en bande',
    ['admin:setGangBoss:command::target'] = 'ID på spiller',
    ['admin:setGangBoss:command::gangName'] = 'Navn på bande',
    ['admin:editGang:menu::title'] = 'Rediger Bande',
    ['admin:editGang:menu::label'] = 'Bande: %s',
    ['admin:editGang:menu::save'] = '<span style="color: rgb(114, 204, 114);">Gem Ændringer</span>',
    ['admin:editGang::edited'] = 'Du ændrede i banden %s',
    ['admin:editGang:menu::remove'] = '<span style="color: rgb(224, 50, 50);">Slet Bande</span>',
    ['admin:editGang:menu::confirmDelete'] = 'Vil du slette banden %s?',
    ['admin:editGang::deleted'] = 'Du slettede banden %s',
    ['admin:editGang:noGang'] = 'Banden %s findes ikke!',
    ['admin:editGang:gangExist'] = 'Banden %s findes allerede!',

    -- Gang
    ['gang:menu:actionMenu::promp'] = 'Tryk ~INPUT_CONTEXT~ for at tilgå ~r~Bande Menuen~s~.',
    ['gang:menu:actionMenu::title'] = 'Bande Menu - %s',
    ['gang:menu:actionMenu::gangInfo'] = 'Bande Information',
    ['gang:menu:actionMenu:gangInfo::title'] = 'Bande Information',
    ['gang:menu:actionMenu:gangInfo::label'] = 'Bande: %s',
    ['gang:menu:actionMenu:gangInfo::members'] = 'Medlemmer: %s/%s',
    ['gang:menu:actionMenu:gangInfo::pushers'] = 'Pushere: %s/%s',
    ['gang:menu:actionMenu::memberList'] = 'Medlemmer',
    ['gang:menu:actionMenu:memberList::name'] = 'Navn',
    ['gang:menu:actionMenu:memberList::rank'] = 'Rank',
    ['gang:menu:actionMenu:memberList::online'] = 'Online',
    ['gang:menu:actionMenu:memberList::actions'] = 'Handlinger',
    ['gang:menu:actionMenu:memberList:action::promote'] = 'Ændre Rank',
    ['gang:menu:actionMenu:memberList:action:promote::selectRank'] = 'Vælg Rank',
    ['gang:menu:actionMenu:memberList:action:promote::promoted'] = 'Du satte %s rank til %s',
    ['gang:menu:actionMenu:memberList:action::remove'] = 'Fjern Medlem',
    ['gang:menu:actionMenu:memberList:action:remove::removed'] = 'Du fjernede %s fra banden',
    ['gang:menu:actionMenu:memberList:action::yourSelf'] = 'Du kan ikke udføre handlinger på dig selv!',
    ['gang:menu:actionMenu:memberList:action::ownRank'] = 'Du kan ikke udføre handlinger på medlemmer som har samme eller højere rank end dig selv!',
    ['gang:menu:actionMenu::memberAdd'] = 'Tilføj Medlem',
    ['gang:menu:actionMenu:memberAdd::title'] = 'Vælg Spiller',
    ['gang:menu:actionMenu:memberAdd:selectRank:title'] = 'Vælg Rank',
    ['gang:menu:actionMenu:memberAdd:selectRank::member'] = 'Medlem',
    ['gang:menu:actionMenu:memberAdd:selectRank::pusher'] = 'Pusher',
    ['gang:menu:actionMenu:memberAdd:added::member'] = 'Du tilføjede %s til banden som Medlem',
    ['gang:menu:actionMenu:memberAdd:added::pusher'] = 'Du tilføjede %s til banden som Pusher',
    ['gang:menu:actionMenu:memberAdd:noSpace::member'] = 'Der er ikke plads til flere medlemmer i banden',
    ['gang:menu:actionMenu:memberAdd:noSpace::pusher'] = 'Der er ikke plads til flere pushere i banden',
    ['gang:menu:actionMenu::rankList'] = 'Ranks',
    ['gang:menu:actionMenu:rankList::id'] = 'ID',
    ['gang:menu:actionMenu:rankList::label'] = 'Label',
    ['gang:menu:actionMenu:rankList::name'] = 'Navn',
    ['gang:menu:actionMenu:rankList::perms'] = 'Tilladelser',
    ['gang:menu:actionMenu:rankList::actions'] = 'Handlinger',
    ['gang:menu:actionMenu:rankList:action::remove'] = 'Fjern Rank',
    ['gang:menu:actionMenu:rankList:action:remove::removed'] = 'Du fjernede ranket %s',
    ['gang:menu:actionMenu:rankList:action:remove::noRem'] = 'Du kan ikke fjerne ranket %s',
    ['gang:menu:actionMenu:rankList:action::perms'] = 'Ændre Tilladelser',
    ['gang:menu:actionMenu:rankList:action:perms:edit::title'] = 'Tilladelser - %s',
    ['gang:menu:actionMenu:rankList:action:perms:edit::savePerms'] = 'Gem Tilladelser',
    ['gang:menu:actionMenu:rankList:action:perms:edit::savedPerms'] = 'Ændrede tilladelser for ranket %s',
    ['gang:menu:actionMenu:rankList:action:perms::noEdit'] = 'Du kan ikke ændre tilladelser på ranket %s',
    ['gang:menu:actionMenu:rankList:action::edit'] = 'Rediger Rank',
    ['gang:menu:actionMenu:rankList:action:edit::title'] = 'Rediger Rank - %s',
    ['gang:menu:actionMenu:rankList:action:edit::label'] = 'Ændre label',
    ['gang:menu:actionMenu:rankList:action:edit::moveUp'] = 'Ryk rank op',
    ['gang:menu:actionMenu:rankList:action:edit::atTop'] = 'Du kan ikke rykke ranket %s mere op',
    ['gang:menu:actionMenu:rankList:action:edit::moveDown'] = 'Ryk rank ned',
    ['gang:menu:actionMenu:rankList:action:edit::atBottom'] = 'Du kan ikke rykke ranket %s mere ned',
    ['gang:menu:actionMenu:rankList:action:edit::newLabel'] = 'Det nye label til ranket %s',
    ['gang:menu:actionMenu:rankList:action:edited::label'] = 'Du ændrede %s label til %s',
    ['gang:menu:actionMenu:rankList:action:edited::moveUp'] = 'Du rykkede %s op på plads %s',
    ['gang:menu:actionMenu:rankList:action:edited::moveDown'] = 'Du rykkede %s ned på plads %s',
    ['gang:menu:actionMenu:rankList:action::noPerm'] = 'Du kan ikke udføre handlinger på din egen rank, eller højere ranks!',
    ['gang:menu:actionMenu::rankAdd'] = 'Tilføj Rank',
    ['gang:menu:actionMenu:rankAdd::title'] = 'Opret nyt rank',
    ['gang:menu:actionMenu:rankAdd::label'] = 'Label: %s',
    ['gang:menu:actionMenu:rankAdd:label::edit'] = 'Navn på ranket',
    ['gang:menu:actionMenu:rankAdd::perms'] = 'Sæt Tilladelser',
    ['gang:menu:actionMenu:rankAdd::save'] = 'Opret Rank',
    ['gang:menu:actionMenu:rankList:action:rankAdd::exist'] = 'Der findes allerede et rank med navnet %s',
    ['gang:menu:actionMenu:rankList:action:rankAdd::added'] = 'Du oprettede ranket %s',
    ['gang:menu:actionMenu::noElements'] = 'Du har ikke adgang til en under-menu',

    ['gang:menu:money::promp'] = 'Tryk ~INPUT_CONTEXT~ for at tilgå ~y~Bande Kassen~s~.',
    ['gang:menu:money::title'] = 'Bande Kasse - %s',
    ['gang:menu:money::account'] = 'Penge i kassen: <span style="color: #fbd734;">%s DKK</span>',
    ['gang:menu:money::insert'] = 'Indsæt penge på kontoen',
    ['gang:menu:money::inserted'] = 'Du indsatte %s DKK på bande kassen.',
    ['gang:menu:money::take'] = 'Tag penge fra kontoen',
    ['gang:menu:money::taken'] = 'Du tog %s DKK fra bande kassen',
    ['gang:menu:money::noMoney'] = 'Der er ikke %s DKK i bande kassen',

    -- Shop
    ['shop:FT::title'] = 'Bande Butik',
    ['shop:menu::promp'] = 'Tryk [~r~E~s~] for at åbne ~b~Bande-Shoppen~s~',
    ['shop:menu::title'] = 'Bande-Shop',
    ['shop:menu::itemLabel'] = '%s - %s DKK',
    ['shop:buyItem::bought'] = 'Du købte %sx %s for %s DKK',
    ['shop:buyItem::noSpace'] = 'Du har ikke plads til %sx %s i dit inventar',
    ['shop:buyItem::amount'] = 'Antal',
    ['shop:buyItem::notNumber'] = 'Du skal angive et tal',
    ['shop:buyItem::noPerm'] = 'Du har ikke tilladelse til at købe %s',

    -- Items
    ['items:key'] = 'Nøgle (%s)',
    ['items:phone'] = 'Bande Telefon (%s)',

    -- Misc
    ['amount'] = 'Antal',
    ['not_number'] = 'Du skal angive et tal',
    ['not_enough_money'] = 'Du har ikke %s DKK kontanter på dig',
    ['yes'] = 'Ja',
    ['no'] = 'Nej',
    ['find_id'] = 'Tryk INSERT for at se IDs',
}